# -*- coding: utf-8 -*-
"""day2.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yepd159lSKu0iokJEacUjAmQICeHMFC6
"""

name = 'Labony Sur'
_age = 22
print (name)

a=10
b=30
c=50

sum= a+b+c
print (sum)

person = input(name)
print (person)

#to know datatype function

student_1 = 'Labony' #string
age_1 = 21 #integer
weight = 22.22 #float

print (type(student_1))
print (type(age_1))
print (type(weight))

#task1 - take number input from user and do sum

num1=input('n1 ')
num2=input ('n2 ')
sum = (num1 + num2)
print (sum)              # this code will retun us string output not a number it just concetinet korce .

num1=int(input('Number 1   '))   #type convertion
num2=int(input('Number 2   '))
sum = (num1 + num2)
print (sum)

#string

a='Bangladesh'
print(a[0:6])

#indexing
bd = 'bangladesh'
print(bd[0::2])

print(bd.upper())

print(bd.lower())